AWSTemplateFormatVersion: 2021-06-07
Description: This template create an Application Load Balancer with EC2 InfraStructure
Parameters:
  InstanceType:
    Description: WebServer EC2 instance type
    Type: String
    Default: t2.micro
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: 'AWS::EC2::KeyPair::KeyName'
    Default: ''  
  AmazonImageID:
    Description: The ID of the Amazon machine image (AMI)
    Type: String
    Default: ''
Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      ImageId: !Ref AmazonImageID 
      Tags:
        - Key: "Testing"
          Value: EC2 | Private Subnet 1
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash -xe
            sudo su
            yum update -y
            yum install -y httpd
            echo "Healthy" > /var/www/html/index.html
            service httpd start