AWSTemplateFormatVersion: '2010-09-09'
Description: This template create an Application Load Balancer with EC2 InfraStructure
Parameters:
  InstanceType:
    Description: WebServer EC2 instance type
    Type: String
    Default: t2.micro
  AmazonImageID:
    Description: The ID of the Amazon machine image (AMI)
    Type: String
    Default: 'ami-0ad704c126371a549'
  IamInstanceProfile:
    Description: The IamInstanceProfile of an instance
    Type: String
    Default: ec2servicerole
Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref AmazonImageID 
      IamInstanceProfile: !Ref IamInstanceProfile
      Tags:
        - Key: "Testing"
          Value: EC2 | Private Subnet 1
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash -xe
            sudo su
            yum update -y
            yum install -y httpd
            echo "Healthy" > /var/www/html/index.html
            service httpd start
            sudo yum install java-1.8.0
            sudo yum install java-1.8.0-openjdk
            sudo wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat/jenkins.repo
            sudo rpm --import https://pkg.jenkins.io/redhat/jenkins.io.key
            sudo yum install jenkins
            sudo service jenkins start
            sudo cat /var/lib/jenkins/secrets/initialAdminPassword