AWSTemplateFormatVersion: '2010-09-09'
Description: This template create an Application Load Balancer with EC2 InfraStructure
Parameters:
  InstanceType:
    Description: WebServer EC2 instance type
    Type: String
    Default: t2.medium
  AmazonImageID:
    Description: The ID of the Amazon machine image (AMI)
    Type: String
    Default: 'ami-0ad704c126371a549'
  IamInstanceProfile:
    Description: The IamInstanceProfile of an instance
    Type: String
    Default: EC2-SSM
Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref AmazonImageID 
      IamInstanceProfile: !Ref IamInstanceProfile
      SecurityGroupIds:
        - sg-088ce769b248d5f05
      Tags:
        - Key: "Testing"
          Value: EC2 | Private Subnet 1
      BlockDeviceMappings:
        - DeviceName: /dev/sdc
          Ebs:
            SnapshotId: snap-041de31327a858319
            VolumeSize: 8
            VolumeType: io1
            Iops: 400
            DeleteOnTermination: true
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash -xe
            sudo su
            yum update -y
            yum install -y httpd
            echo "Healthy" > /var/www/html/index.html
            service httpd start
            yum install java-1.8.0 -y
            yum install java-1.8.0-openjdk -y
            wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat/jenkins.repo
            rpm --import https://pkg.jenkins.io/redhat/jenkins.io.key
            yum install jenkins -y
            service jenkins start 
            cat /var/lib/jenkins/secrets/initialAdminPassword

            